[package]
name = "artemis-template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
async-trait = "0.1.77"
ethers = "2"
artemis-core = { git = "https://github.com/paradigmxyz/artemis" }